In [ ]:
!pip install scikit-learn
!pip install -U spacy
!python -m spacy download en
!python -m spacy download en_core_web_sm

     |████████████████████████████████| 10.0MB 2.8MB/s 
     |████████████████████████████████| 2.1MB 46.8MB/s 
  Found existing installation: thinc 7.4.0
    Uninstalling thinc-7.4.0:
      Successfully uninstalled thinc-7.4.0
  Found existing installation: spacy 2.2.4
    Uninstalling spacy-2.2.4:
      Successfully uninstalled spacy-2.2.4
     |████████████████████████████████| 12.1MB 653kB/s 
  Created wheel for en-core-web-sm: filename=en_core_web_sm-2.3.1-cp36-none-any.whl size=12047111 sha256=dbab1edd69b43b2dd923124e395332651c8d25de90788658373bf94bcd3bf252
  Stored in directory: /tmp/pip-ephem-wheel-cache-2fsgw3tw/wheels/2b/3f/41/f0b92863355c3ba34bb32b37d8a0c662959da0058202094f46
Successfully built en-core-web-sm
  Found existing installation: en-core-web-sm 2.2.5
    Uninstalling en-core-web-sm-2.2.5:
      Successfully uninstalled en-core-web-sm-2.2.5
✔ Download and installation successful
You can now load the model via spacy.load('en_core_web_sm')
✔ Linking successful
/usr/lo

In [ ]:
import spacy
from spacy import displacy
import pandas as pd

In [ ]:
nlp = spacy.load('en_core_web_sm')

In [ ]:
dfs = pd.read_csv('/content/AmazonCSV.csv')
for i in range(0, 5):
  print(dfs.iloc[1])
dfs['Sentiment'].value_counts()
dfs.isnull().sum()
X = dfs['Review']
y = dfs['Sentiment']


Review       Good case, Excellent value.
Sentiment                              1
Name: 1, dtype: object
Review       Good case, Excellent value.
Sentiment                              1
Name: 1, dtype: object
Review       Good case, Excellent value.
Sentiment                              1
Name: 1, dtype: object
Review       Good case, Excellent value.
Sentiment                              1
Name: 1, dtype: object
Review       Good case, Excellent value.
Sentiment                              1
Name: 1, dtype: object


In [ ]:
sent = nlp.create_pipe('sentencizer')

nlp.add_pipe(sent, before='parser')

In [ ]:
from spacy.lang.en.stop_words import STOP_WORDS
stopwords = list(STOP_WORDS)
print(stopwords)
print("Number of stopwords= ",len(stopwords))

['move', 'whole', 'everyone', 'except', 'top', 'against', 'say', 'indeed', 'below', 'across', 'does', 'least', 'just', 'mostly', 'sometime', 'therefore', 'thereafter', 'they', 'nothing', 'this', "'m", 'whence', 'mine', 'will', 'while', 'on', 'same', 'many', 'you', 'to', 'neither', 'besides', 'had', 'herself', 'her', 'various', '‘s', 'either', 'who', "'s", 'thru', 'towards', 'already', 'before', 'after', 'might', 'enough', 'must', 'afterwards', 'do', 'both', 'by', 'and', 'once', 'seems', 'between', 'may', 'next', 'it', 'much', 'part', 'five', 'fifty', 'more', 'through', 'twenty', 'hereby', 'under', "n't", "'re", 'my', 'anything', '’ve', 'even', 'toward', 'sometimes', 'seem', 'therein', 'down', 'no', 'such', 'when', 'further', 'quite', 'really', 'sixty', 'amongst', 'were', 'beside', 'all', 'those', 'make', 'up', 'each', 'nevertheless', 'full', 'yours', 'n’t', 'behind', 'ourselves', 'last', 'somehow', 'been', 'so', 'very', 'side', 'rather', 'give', 'others', 'empty', 'than', 'every', 'or'

In [ ]:
for i in range(2):
  #print(dfs.loc[i, 'Review'])
  doc = nlp(dfs.loc[i, 'Review'])
  for sent in doc.sents:
    print(sent,'\n')
  print('(Stopwords in the sentence:) \n')
  for token in doc:
    if token.is_stop == False:
        print(token)
  print('(Lemmatization: [Text, Lemma, POS]) \n')
  
  for lem in doc:
    print(lem.text, lem.lemma_, lem.pos_)
  displacy.render(doc, style = 'dep', jupyter=True)
  print('-------------------------')


So there is no way for me to plug it in here in the US unless I go by a converter. 

(Stopwords in the sentence:) 

way
plug
converter
.
(Lemmatization: [Text, Lemma, POS]) 

So so CCONJ
there there PRON
is be AUX
no no DET
way way NOUN
for for ADP
me -PRON- PRON
to to PART
plug plug VERB
it -PRON- PRON
in in ADP
here here ADV
in in ADP
the the DET
US US PROPN
unless unless SCONJ
I -PRON- PRON
go go VERB
by by ADP
a a DET
converter converter NOUN
. . PUNCT


-------------------------
Good case, Excellent value. 

(Stopwords in the sentence:) 

Good
case
,
Excellent
value
.
(Lemmatization: [Text, Lemma, POS]) 

Good good ADJ
case case NOUN
, , PUNCT
Excellent excellent ADJ
value value NOUN
. . PUNCT


-------------------------


In [ ]:
for i in range(2):
  doc = nlp(dfs.loc[i, 'Review'])
  displacy.render(doc, style = 'ent', jupyter=True)

/usr/local/lib/python3.6/dist-packages/spacy/displacy/__init__.py:189: UserWarning: [W006] No entities to visualize found in Doc object. If this is surprising to you, make sure the Doc was processed using a model that supports named entity recognition, and check the `doc.ents` property manually if necessary.
  warnings.warn(Warnings.W006)


**Tokenization**

In [ ]:
import string

punct = string.punctuation
print(punct)

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~


In [ ]:
def text_data_cleaning(sentence):
    print('Sentence is: \n',sentence)
    doc = nlp(sentence)
    
    tokens = []
    for token in doc:
        if token.lemma_ != "-PRON-":
            temp = token.lemma_.lower().strip()
        else:
            temp = token.lower_
        tokens.append(temp)
    
    cleaned_tokens = []
    for token in tokens:
        if token not in stopwords and token not in punct:
            cleaned_tokens.append(token)
    print('Cleaned Tokens from the sentence are:')
    # print('----------------------------------')
    return cleaned_tokens

In [ ]:
for review in X:
  text_data_cleaning(review)
  

Sentence is: 
 So there is no way for me to plug it in here in the US unless I go by a converter.
Cleaned Tokens from the sentence are:
Sentence is: 
 Good case, Excellent value.
Cleaned Tokens from the sentence are:
Sentence is: 
 Great for the jawbone.
Cleaned Tokens from the sentence are:
Sentence is: 
 Tied to charger for conversations lasting more than 45 minutes.MAJOR PROBLEMS!!
Cleaned Tokens from the sentence are:
Sentence is: 
 The mic is great.
Cleaned Tokens from the sentence are:
Sentence is: 
 I have to jiggle the plug to get it to line up right to get decent volume.
Cleaned Tokens from the sentence are:
Sentence is: 
 If you have several dozen or several hundred contacts, then imagine the fun of sending each of them one by one.
Cleaned Tokens from the sentence are:
Sentence is: 
 If you are Razr owner...you must have this!
Cleaned Tokens from the sentence are:
Sentence is: 
 Needless to say, I wasted my money.
Cleaned Tokens from the sentence are:
Sentence is: 
 What a wa

**Vector Feature Engineering (TF-IDF)**

In [ ]:
from sklearn.svm import LinearSVC
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(tokenizer = text_data_cleaning)
classifier = LinearSVC()

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)
print(X_train.shape, X_test.shape)

(800,) (200,)


In [ ]:
from sklearn.pipeline import Pipeline
clf = Pipeline([('tfidf', tfidf), ('clf', classifier)])
clf.fit(X_train, y_train)

Sentence is: 
 doesn't hold charge.
Cleaned Tokens from the sentence are:
Sentence is: 
 all it took was one drop from about 6 inches above the kitchen counter and it was cracked.i am not impressed and i am not laughing.
Cleaned Tokens from the sentence are:
Sentence is: 
 do not buy if you want to use the holster.
Cleaned Tokens from the sentence are:
Sentence is: 
 i have purchased these for both family and friends, and all enjoy their clarity and ease of use
Cleaned Tokens from the sentence are:
Sentence is: 
 horrible, horrible protector.
Cleaned Tokens from the sentence are:
Sentence is: 
 piece of trash.
Cleaned Tokens from the sentence are:
Sentence is: 
 great value.
Cleaned Tokens from the sentence are:
Sentence is: 
 works for me.
Cleaned Tokens from the sentence are:
Sentence is: 
 plug was the wrong size.
Cleaned Tokens from the sentence are:
Sentence is: 
 awkward to use and unreliable.
Cleaned Tokens from the sentence are:
Sentence is: 
 the one big drawback of the mp3 pl

Pipeline(memory=None,
         steps=[('tfidf',
                 TfidfVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.float64'>,
                                 encoding='utf-8', input='content',
                                 lowercase=True, max_df=1.0, max_features=None,
                                 min_df=1, ngram_range=(1, 1), norm='l2',
                                 preprocessor=None, smooth_idf=True,
                                 stop_words=None, strip_accents=None,
                                 sublinear_tf=False,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=<function text_data_cleaning at 0x7fb123521d08>,
                                 use_idf=True, vocabulary=None)),
                ('clf',
                 LinearSVC(C=1.0, class_weight=None, dual=True,
                           fit_intercept

In [ ]:
y_pred = clf.predict(X_test)

Sentence is: 
 thanks again to amazon for having the things i need for a good price!
Cleaned Tokens from the sentence are:
Sentence is: 
 the tracfonewebsite is user friendly and makes it easy toactivate, etc.
Cleaned Tokens from the sentence are:
Sentence is: 
 i would highly recommend this product.
Cleaned Tokens from the sentence are:
Sentence is: 
 this does not fit the palm tungsten e2 and it broke the first time i tried to plug it in.
Cleaned Tokens from the sentence are:
Sentence is: 
 i highly recommend this device to everyone!
Cleaned Tokens from the sentence are:
Sentence is: 
 it works fine on my motorola 325 cellphone, and a lot better than the worn-out battery did.
Cleaned Tokens from the sentence are:
Sentence is: 
 don't make the same mistake that i did and please don't buy this phone.
Cleaned Tokens from the sentence are:
Sentence is: 
 i got the aluminum case for my new palm vx and it worked really well--it has protected my handheld perfectly so far.
Cleaned Tokens fro

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(y_test, y_pred))
confusion_matrix(y_test, y_pred)

              precision    recall  f1-score   support

           0       0.75      0.78      0.77        93
           1       0.81      0.78      0.79       107

    accuracy                           0.78       200
   macro avg       0.78      0.78      0.78       200
weighted avg       0.78      0.78      0.78       200



array([[73, 20],
       [24, 83]])

In [ ]:
clf.predict(['Wow, this is amzing lesson'])

['wow', 'amze', 'lesson']
----------------------------------


array([1])

In [ ]:
clf.predict(['Wow, this sucks'])

['wow', 'suck']
----------------------------------


array([0])

In [ ]:
clf.predict(['Worth of watching it. Please like it'])

['worth', 'watch', 'like']
----------------------------------


array([1])

In [ ]:
clf.predict(['Loved it. amazing'])

['love', 'amazing']
----------------------------------


array([1])